myyel/Controllers/AdminController.cs
using Microsoft.AspNetCore.Mvc.Formatters;
using myyel.Entity;
using myyel.Identity;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Drawing;
using System.Drawing.Imaging;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Net.Mime;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace myyel.Controllers
{
    [Authorize(Roles = "admin")]
    public class AdminController : Controller
    {
        IdentityDataContext _identity = new IdentityDataContext();
        DataContext _context = new DataContext();

        /*todo: İmg src yolu servera göre değişecek*/
        private bool SendEmailAll(List<ApplicationUser> applicationUsers, SendMail sendMail, List<SendMailPhoto> sendMailPhotos)
        {
            try
            {
                foreach (var item in applicationUsers)
                {
                    string imgHtml = "";
                    foreach (var i in sendMailPhotos) 
                    {
                        imgHtml += "<img src='https://www.myyeldesign.com/Admin/SendMailPhotoDetails/" + i.Id + " .jpg' class='img-fluid'/>";
                    };

                    string htmlBody = "<div style = 'width:70%; margin-left:2vw;' >" +

          "<h2>" + sendMail.Title + " </h2><hr />" +
          imgHtml +
                        "<p>" + sendMail.Content + "</p>" +

                    "<h3 style = 'margin-top: 8vw; ' > Yaratıcı Tasarımlar </h3>" +
                        "<h4 style = 'margin-top:6vw;' > İrtibat </h4>" +
                        "<p> Tel: 0 544 295 19 87 </p>" +
                        "<p> Mail: myyeldesign@gmail.com </p>" +

                        "</div>";

                    /*AlternateView avHtml = AlternateView.CreateAlternateViewFromString(htmlBody,null,MediaTypeNames.Text.Html);

                    MailMessage mail = new MailMessage();
                    mail.AlternateViews.Add(avHtml);

                    foreach (var i in sendMailPhotos)
                    {
                        LinkedResource inline = new LinkedResource("D:/masaustu/myyel_site/myyel/Content/mail_images/" + i.Id + " .jpg", MediaTypeNames.Image.Jpeg);
                        inline.ContentId = Guid.NewGuid().ToString();
                        avHtml.LinkedResources.Add(inline);
                        Attachment att = new Attachment("D://masaustu//myyel_site//myyel//Content//mail_images//"+i.Id+" .jpg");
                        att.ContentDisposition.Inline = true;
                        mail.Attachments.Add(att);
                    };*/


                    MailMessage mail = new MailMessage();
                    mail.To.Add(item.Email);
                    mail.From = new MailAddress("myyeldesign@gmail.com");
                    mail.Subject = sendMail.Title;
                    mail.Body = htmlBody;
                    mail.IsBodyHtml = true;
                    mail.SubjectEncoding = Encoding.Default;
                    /*for (int i = 1; i-1 < sendMailPhotos.Count(); i++)
                    {
                        mail.Attachments.Add(new Attachment("D://masaustu//myyel_site//myyel//Content//mail_images//"+i+" .jpg", MediaTypeNames.Application.Octet));
                    }*/
                    mail.BodyEncoding = Encoding.Default;
                    SmtpClient smtp = new SmtpClient();
                    smtp.Credentials = new NetworkCredential("myyeldesign@gmail.com", "xefyzc11");
                    smtp.Port = 587;
                    smtp.Host = "smtp.gmail.com";
                    smtp.EnableSsl = true;
                    smtp.Send(mail);
                }
                return true;
            }
            catch (Exception ex)
            {
                ViewBag.hata = ex;
                return false;
            }

        }

        // GET: Admin
        public ActionResult Index()
        {
            Counter counter = new Counter();
            counter = _context.counters.FirstOrDefault();
            ViewBag.visitor = counter.Count.ToString();
            ViewBag.userCount = _identity.Users.Count();
            ViewBag.messageCount = _context.HomeFormEntites.Count();
            return View(_context.HomeEntities.Where(i => i.Id == 1).FirstOrDefault());
        }

        public ActionResult HomeEdit()
        {
            return View(_context.HomeEntities.Where(i => i.Id == 1).FirstOrDefault());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult HomeEdit([Bind(Include = "Id,SliderItemA1,SliderItemA2,SliderItemB1,SliderItemB2,"+
            "SliderItemC1,SliderItemC2,About1,About2,ProjectImage1,ProjectImage2,ProjectImage3,AdTitle1,AdTitle2,"+
            "AdItemImageA,AdItemImageB,AdItemImageC,AdItemImageAText1,AdItemImageAText2,AdItemImageBText1,"+
            "AdItemImageBText2,AdItemImageCText1,AdItemImageCText2,LessonTitle,LessonItem1,LessonItem2,LessonItem3,"+
            "LessonItem4,LessonItem5,LessonItem6,ContactTitleA,ContactTitleB,ContactPhone,ContactFacebook,ContactMail,"+
            "ContactInsta,FooterImage,FooterText")] HomeEntity homeEntity)
        {
            if (ModelState.IsValid)
            {
                _context.Entry(homeEntity).State = EntityState.Modified;
                _context.SaveChanges();
                return RedirectToAction("Index", "Home");
            }
            return View(homeEntity);
        }

        [HttpGet]
        public ActionResult ImageEdit(int? id)
        {
            id = 1;
            HomeEntity homeEntity = _context.HomeEntities.Find(id);
            if (homeEntity == null)
            {
                return HttpNotFound();
            }
            return View(homeEntity);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ImageEdit(string id, HttpPostedFileBase uploadedImage)
        {
            if (uploadedImage == null)
            {
                return RedirectToAction("HomeEdit");

            }
            else
            {
                string ImageFileName = id + " .jpg";
                string FolderPath = Path.Combine(Server.MapPath("~/Content/img"), ImageFileName);
                if (System.IO.File.Exists(FolderPath))
                {
                    System.IO.File.Delete(FolderPath);
                }

                uploadedImage.SaveAs(FolderPath);

                return RedirectToAction("Index");
            }
        }

        [HttpGet]
        public ActionResult ProjectImage()
        {
            var homeEntity = _context.HomeEntities.Find(1);
            ViewData["logo"] = homeEntity.FooterImage;
            ViewData["text"] = homeEntity.FooterText;
            return View(_context.ProjectImageEntities.ToList());
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ProjectImage([Bind(Include = "Id")] ProjectImageEntity projectImageEntity,
            HttpPostedFileBase uploadedImage)
        {
            if (uploadedImage == null)
            {
                ViewData["hata"] = "Yükleme İşlemi başarısız";
                var homeEntity = _context.HomeEntities.Find(1);
                ViewData["logo"] = homeEntity.FooterImage;
                ViewData["text"] = homeEntity.FooterText;
                return View(_context.ProjectImageEntities.ToList());
            }
            else
            {
                if (ModelState.IsValid)
                {
                    _context.ProjectImageEntities.Add(projectImageEntity);
                    _context.SaveChanges();
                }

                string ImageFileName = projectImageEntity.Id + " .jpg";
                string FolderPath = Path.Combine(Server.MapPath("~/Content/portfoy"), ImageFileName);
                if (System.IO.File.Exists(FolderPath))
                {
                    System.IO.File.Delete(FolderPath);
                }

                uploadedImage.SaveAs(FolderPath);
                var homeEntity = _context.HomeEntities.Find(1);
                ViewData["sonuc"] = "Yükleme işlemi başarılı";
                ViewData["logo"] = homeEntity.FooterImage;
                ViewData["text"] = homeEntity.FooterText;
                return View(_context.ProjectImageEntities.ToList());
            }
        }

        [HttpGet]
        public ActionResult ProjectDelete(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Error", "Home");
            }
            ProjectImageEntity projectImageEntity = _context.ProjectImageEntities.Find(id);
            if (projectImageEntity == null)
            {
                return HttpNotFound();
            }
            _context.ProjectImageEntities.Remove(projectImageEntity);
            _context.SaveChanges();
            string ImageFileName = id.ToString() + " .jpg";
            string FolderPath = Path.Combine(Server.MapPath("~/Content/portfoy"), ImageFileName);
            if (System.IO.File.Exists(FolderPath))
            {
                System.IO.File.Delete(FolderPath);
            }
            return RedirectToAction("ProjectImage");
        }

        [HttpGet]
        public ActionResult Blog()
        {
            return View(_context.HomeEntities.Find(1));
        }

        [HttpGet]
        public ActionResult BlogCreate()
        {
            var homeEntity = _context.HomeEntities.Find(1);
            ViewData["logo"] = homeEntity.FooterImage;
            ViewData["text"] = homeEntity.FooterText;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult BlogCreate([Bind(Include = "Id, BlogTitle, BlogItem")] BlogEntity blogEntity,
            HttpPostedFileBase uploadedImage)
        {
            if (uploadedImage == null)
            {
                ViewData["hata"] = "Yükleme İşlemi başarısız";
                var homeEntity = _context.HomeEntities.Find(1);

myyel/Controllers/UserController.cs
using myyel.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using myyel.Entity;
using System.Data.Entity;
using System.IO;
using System.Web.Routing;
using System.Data.Entity.Validation;
using myyel.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System.Threading.Tasks;

namespace myyel.Controllers
{
    [Authorize(Roles = "user")]
    public class UserController : Controller
    {
        IdentityDataContext _identity = new IdentityDataContext();
        DataContext _context = new DataContext();
        private UserManager<ApplicationUser> userManager;
        private RoleManager<ApplicationRole> roleManager;

        public UserController()
        {
            var userStore = new UserStore<ApplicationUser>(new IdentityDataContext());
            userManager = new UserManager<ApplicationUser>(userStore);

            var roleStore = new RoleStore<ApplicationRole>(new IdentityDataContext());
            roleManager = new RoleManager<ApplicationRole>(roleStore);
        }

        [HttpGet]
        public ActionResult UserOperations(string ad)
        {
            ad = User.Identity.Name;
            if (ad == "")
            {
                return RedirectToAction("Login", "Account");
            }

            ApplicationUser applicationUser = new ApplicationUser();
            var edituser = _identity.Users.Where(i => i.UserName == ad).FirstOrDefault();

            if (edituser == null)
            {
                return RedirectToAction("Error", "Home");
            }
            applicationUser.Id = edituser.Id;
            applicationUser.Name = edituser.Name;
            applicationUser.Surname = edituser.Surname;
            applicationUser.UserName = edituser.UserName;
            applicationUser.Email = edituser.Email;

            ViewBag.applicationuser = applicationUser;
            ViewBag.homeEntity = _context.HomeEntities.Find(1);
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult UserOperations([Bind(Include = "Email")] EmailChange emailChange)
        {
            string name = User.Identity.Name;
            string email = emailChange.Email;
            ApplicationUser applicationUser = new ApplicationUser();
            applicationUser = _identity.Users.Where(i => i.UserName == name).FirstOrDefault();

            if (ModelState.IsValid)
            {
                applicationUser.Email = email;
                _identity.SaveChanges();

                return RedirectToAction("Index", "Home");
            }

            ViewBag.applicationuser = applicationUser;
            ViewBag.hata = "Geçerli bir email adresi giriniz";
            ViewBag.homeEntity = _context.HomeEntities.Find(1);
            return View(emailChange);
        }

        [HttpGet]
        public ActionResult UserPasswordChange()
        {
            string name = User.Identity.Name;
            if (name == "")
            {
                return RedirectToAction("Login", "Account");
            }

            var edituser = _identity.Users.Where(i => i.UserName == name).FirstOrDefault();

            if (edituser == null)
            {
                return RedirectToAction("Error", "Home");
            }

            ViewBag.homeEntity = _context.HomeEntities.Find(1);
            return View();
        }

        [HttpPost]
        public ActionResult UserPasswordChange(PasswordChange passwordChange)
        {
            string name = User.Identity.Name;
            ApplicationUser applicationUser = new ApplicationUser();
            applicationUser = _identity.Users.Where(i => i.UserName == name).FirstOrDefault();
            IdentityResult result = userManager.ChangePassword(applicationUser.Id, passwordChange.ExPassword, passwordChange.Password);

            if (!result.Succeeded)
            {
                ViewBag.applicationuser = applicationUser;
                ViewBag.homeEntity = _context.HomeEntities.Find(1);
                return View(passwordChange);
            }

            return RedirectToAction("Index", "Home");
        }
        public ActionResult UserDelete(string userName)
        {
            userName = User.Identity.Name;
            if (userName == null)
            {
                var authManager = HttpContext.GetOwinContext().Authentication;
                authManager.SignOut();

                ViewBag.homeEntity = _context.HomeEntities.Find(1);
                return RedirectToAction("Error", "Home");
            }
            else
            {
                var authManager = HttpContext.GetOwinContext().Authentication;
                authManager.SignOut();

                ApplicationUser applicationUser = new ApplicationUser();
                applicationUser = _identity.Users.Where(i => i.UserName == userName).FirstOrDefault();


                if (ModelState.IsValid)
                {
                    _identity.Users.Remove(applicationUser);
                    _identity.SaveChanges();

                    ViewBag.homeEntity = _context.HomeEntities.Find(1);
                    return RedirectToAction("Index", "Home");
                }

                ViewBag.homeEntity = _context.HomeEntities.Find(1);
                return RedirectToAction("Error", "Home");
            }
        }
    }
}

myyel/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

myyel/Views/Shared/admin_home_layout.cshtml
@using myyel.Entity
@model HomeEntity

<!DOCTYPE html>
<html>
<head>
    <title style="color:#626262">MyyeL Design</title>
    <meta name="viewport" content="width=device-width initial-scale=1, shrink-to-fit=no" />
    <link rel="shortcut icon" href="~/Content/img/logo02.ico" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link href="~/Content/Site.css" rel="stylesheet" />
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="~/Content/Swiper.css" />
    <link rel="stylesheet" href="~/Content/AdminHomeEdit.css" />

</head>
<body>
    <!--navbar-->
    <div class="menu-fixed">
        <div class="menu-left">
            <ul class="nav-logo2">
                <li>
                    <a href="#"><img src="~/Content/img/logo02.png" alt="logo" /></a>
                </li>
                <li>
                    <div class="burger2" style="margin-top:1vw" alt="slide-navbar" title="Menu">
                        <div class="line1"></div>
                        <div class="line2"></div>
                        <div class="line3"></div>
                    </div>
                </li>
                <li class="nav-close">X</li>
            </ul>
        </div>
        <div class="menu-right">
            <div class="nav-links2">
                <div class="menu-right-1" title="Anasayfa" alt="MainPage">
                    @Html.ActionLink("Anasayfa", "Index", "Home")
                </div>
                <div class="menu-right-1" title="Hakkımızda" alt="About">
                    @Html.ActionLink("Hakkımızda", "About", "Home")
                </div>
                <div class="menu-right-1" title="Projeler" alt="Projects">
                    @Html.ActionLink("Projeler", "Project", "Home")
                </div>
                <div class="menu-right-1" title="Kurs" alt="Course">
                    @Html.ActionLink("Kurs", "Course", "Home")
                </div>
                <div class="menu-right-1" title="Blog" alt="Blogs">
                    @Html.ActionLink("Blog", "Blog", "Home")
                </div>
                <div class="menu-right-1" title="İletişim" alt="Contact">
                    @Html.ActionLink("İletişim", "Contact", "Home")
                </div>
                @if (Request.IsAuthenticated)
                {
                    <div id="ns" alt="User Name" class="menu-right-2">@User.Identity.Name.ToString()</div>

                    if (User.Identity.Name == "myyel")
                    {
                        <div class="menu-right-4">
                            <a href="/Admin" class="menu-btn-4" alt="Admin Management">Yönetim<br />İşlemleri</a>
                            <a href="/Account/Logout" class="menu-btn-3" alt="Log out">Çıkış yap</a>
                        </div>
                    }
                    else
                    {
                        <div class="menu-right-4">
                            <a href="@Url.Action("UserOperations","User", new { @id = User.Identity.Name.ToString() })" class="menu-btn-4" alt="Account Management">
                                Kullanıcı<br />İşlemleri
                            </a>
                            <a href="/Account/Logout" class="menu-btn-3" alt="Log out">Çıkış yap</a>
                        </div>
                    }
                }
                else
                {
                    <div class="menu-right-2"></div>
                    <div class="menu-right-3">
                        <div class="menu-btn-2" alt="Register">Kayıt ol</div>
                        <div class="menu-btn" alt="Login">Giriş yap</div>
                    </div>
                }
            </div>
        </div>
    </div>

    @RenderBody()

    <script src="https://unpkg.com/swiper/swiper-bundle.min.js"></script>
    <script src="~/Content/main.js"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script>
        var swiper = new Swiper(".mySwiper", {
            slidesPerView: 3,
            spaceBetween: 30,
            slidesPerGroup: 1,
            loop: true,
            centeredSlides: true,
            grabCursor: true,
            loopFillGroupWithBlank: true,
            autoplay: true,
            pagination: {
                el: ".swiper-pagination",
                clickable: true,
            },
            navigation: {
                nextEl: ".swiper-button-next",
                prevEl: ".swiper-button-prev",
            },
        });
    </script>
</body>
</html>

myyel/Views/Shared/admin_layout.cshtml
@using myyel.Entity
@model HomeEntity

<!DOCTYPE html>
<html>
<head>
    <title style="color:#626262">MyyeL Design</title>
    <meta name="viewport" content="width=device-width initial-scale=1, shrink-to-fit=no" />
    <meta name="robots" content="noindex, nofollow"
    <link rel="shortcut icon" href="~/Content/img/logo02.ico" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link href="~/Content/Site.css" rel="stylesheet" />
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="~/Content/Swiper.css" />
    <link rel="stylesheet" href="~/Content/Admin-Site.css" />
    <link rel="stylesheet" href="~/Content/AdminHomeEdit.css" />

</head>
<body>
    <!--Admin_Navbar-->
    <div class="admin-navbar">
        <div class="admin-navbar-bg">
            <div class="admin-navbar-left">
                <a href="~/Admin/Index"><img src="~/Content/img/logo-yan.png" /></a>
            </div>
            <div class="admin-navbar-right">
                <div class="admin-navbar-right-item">
                    @Html.ActionLink("Anasayfa", "Index", "Home")
                </div>
                <div class="admin-navbar-right-item">
                    @Html.ActionLink("Anasayfa İşlemleri", "HomeEdit", "Admin")
                </div>
                <div class="admin-navbar-right-item">
                    @Html.ActionLink("Kullanıcı İşlemleri", "UserPage", "Admin")
                </div>
                <div class="admin-navbar-right-item">
                    @Html.ActionLink("Proje Resmi Ekle", "ProjectImage", "Admin")
                </div>
                <div class="admin-navbar-right-item">
                    @Html.ActionLink("Blog İşlemleri", "Blog", "Admin")
                </div>
            </div>
        </div>

        <div class="admin-main-bg">
            @RenderBody()
        </div>
    </div>
    <hr />
    <!--Footer-->
    <footer class="footer-bg" style="margin-left:6vw;">
        <div class="footer-inside">
            <div class="footer-logo">
                <img src="~/Content/img/@Model.FooterImage .png" alt="Myyel Logo" />
            </div>
            <div class="footer-text">
                <h2>@Model.FooterText</h2>
            </div>
            <div class="footer-copy">
                <p>&copy;2021-MyyeL Design Tüm Hakları Saklıdır</p>
            </div>
        </div>
    </footer>

</body>
</html>